### PR TITLE
Fix Spring Security 5.1 Startup

### PR DESCRIPTION
**Pull request by rwinch**

### CODE REVIEW

**Review by mraible — APPROVED** [review]

**Comment by mraible** [comment]
Thanks, @rwinch! BTW, is there an easy way to get the "end_session_endpoint" value from https://dev-158606.oktapreview.com/oauth2/default/.well-known/openid-configuration? If so, I wouldn't need to manually construct the logout URI in `UserController`.

**Comment by rwinch** [comment]
@mraible Not that the moment. Can you please create a ticket for that?

**Comment by mraible** [comment]
Ticket at https://github.com/spring-projects/spring-security/issues/5540. 

@rwinch This PR fixes startup, but I still get the following error when navigating to http://localhost:8080/login.

```
2018-07-18 13:24:05.271 ERROR 42575 --- [io-8080-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

org.springframework.security.oauth2.client.resource.UserRedirectRequiredException: A redirect is required to get the users approval
        at org.springframework.security.oauth2.client.token.grant.code.AuthorizationCodeAccessTokenProvider.getRedirectForAuthorization(AuthorizationCodeAccessTokenProvider.java:359) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
        at org.springframework.security.oauth2.client.token.grant.code.AuthorizationCodeAccessTokenProvider.obtainAccessToken(AuthorizationCodeAccessTokenProvider.java:205) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
        at org.springframework.security.oauth2.client.OAuth2RestTemplate.acquireAccessToken(OAuth2RestTemplate.java:221) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
        at org.springframework.security.oauth2.client.OAuth2RestTemplate.getAccessToken(OAuth2RestTemplate.java:173) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
        at org.springframework.security.oauth2.client.filter.OAuth2ClientAuthenticationProcessingFilter.attemptAuthentication(OAuth2ClientAuthenticationProcessingFilter.java:105) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212) ~[spring-security-web-5.1.0.BUILD-SNAPSHOT.jar:5.1.0.BUILD-SNAPSHOT]
```

**Comment by rwinch** [comment]
@mraible Ok I will try and figure that out. I'm somewhat allergic to JavaScript, but perhaps that part won't bee to bad.

**Comment by mraible** [comment]
@rwinch There's no JavaScript involved. I expect it to redirect to Okta with my OIDC settings, just like it does when I use the OAuth 2.0 properties.

```yaml
security:
  oauth2:
    client:
      access-token-uri: https://dev-158606.oktapreview.com/oauth2/default/v1/token
      user-authorization-uri: https://dev-158606.oktapreview.com/oauth2/default/v1/authorize
      client-id: XXX
      client-secret: YYY
      scope: openid email profile
    resource:
      user-info-uri: https://dev-158606.oktapreview.com/oauth2/default/v1/userinfo
```

**Pull request merged**
